name: Deploy Azure Resources with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test-github-actions-iac
    steps:
    - name: Checkout Code
      uses: actions/checkout@v7
    - name: Azure Login via Secret
      uses: azure/login@v2 # Note: uses 'creds' parameter
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      
